package com.softdesign.devintensive.data.storage.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.softdesign.devintensive.data.storage.models.User;
import com.softdesign.devintensive.data.storage.models.Repository;
import com.softdesign.devintensive.data.storage.models.Like;

import com.softdesign.devintensive.data.storage.models.UserDao;
import com.softdesign.devintensive.data.storage.models.RepositoryDao;
import com.softdesign.devintensive.data.storage.models.LikeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig repositoryDaoConfig;
    private final DaoConfig likeDaoConfig;

    private final UserDao userDao;
    private final RepositoryDao repositoryDao;
    private final LikeDao likeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        repositoryDaoConfig = daoConfigMap.get(RepositoryDao.class).clone();
        repositoryDaoConfig.initIdentityScope(type);

        likeDaoConfig = daoConfigMap.get(LikeDao.class).clone();
        likeDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        repositoryDao = new RepositoryDao(repositoryDaoConfig, this);
        likeDao = new LikeDao(likeDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Repository.class, repositoryDao);
        registerDao(Like.class, likeDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        repositoryDaoConfig.getIdentityScope().clear();
        likeDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RepositoryDao getRepositoryDao() {
        return repositoryDao;
    }

    public LikeDao getLikeDao() {
        return likeDao;
    }

}
